### ISSUE TITLE
Space Beach, I don't want to write code, explorer query fails

### ISSUE THREAD

**Issue by ausimity** [apollographql/hack-the-supergraph#30]
The Query provided in the instructions for this path fails when pasted into explorer without changes.  
![image](https://user-images.githubusercontent.com/11153249/193343422-1f3908e0-d405-4479-9329-25d48634f868.png)

**Comment by michael-watson** [comment]
We will be replacing this with `rover dev` to ensure `@defer` is available to them. The user might have to click a button in studio to "update to the latest" if they have previously used Studio and have a cached version.
