### ISSUE TITLE
Solar Seas, I don't want to write code, no completed schema

### ISSUE THREAD

**Issue by ausimity** [apollographql/hack-the-supergraph#33]
Seems we should have a schema_final.graphql (or something similar) in the solar-seas folder for the people who do not want to write code.  Alternatively, provide what the solar-seas schema should look like (in whole) upon completion as part of this track so it can be easily copied into the schema file.

**Comment by michael-watson** [comment]
We changed the "I don't want to write code" to having the completed schema for each substation
